project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd
      - licence.qmd

format:
  html:
    bibliography: references.bib
    theme: flatly
    css: styles.css
    toc: true

execute: 
  freeze: auto

