---
title: "Schedule & Materials"
---
### October to December 2023

| Week | Date | Topic | Slides | Other Materials |
|------|------|------|------| ------|
| 1 | 25/10/2023 | Welcome and introduction |[slides](slides/d01_01_welcome.html){target="_blank"} |      |
| N/A | 01/11/2023 | No workshop (public holiday) |      |      |
| 2 | 08/11/2023 | Basic data exploration and data viz|[workshop slides](slides/d01_02_data_exploration_basics.html){target="_blank"} \\ [installing R](slides/d01_03_installing_R.html){target="_blank"}|[live coding output](code/week2_basic_data_exploration_live_coding.html){target="_blank"} \\ [source](https://github.com/ibsneuro/uoc_datasci/blob/main/code/week2_basic_data_exploration_live_coding.qmd){target="_blank"} |
| 3 | 15/11/2023 | Data exploration part 2 | [slides](slides/d01_04_data_exploration2.html){target="_blank"}| [live coding template](https://github.com/ibsneuro/uoc_datasci/blob/main/code/session3_live.qmd){target="_blank"} \\ [live coding output](code/session3_live_complete.html){target="_blank"} \\ [source](https://github.com/ibsneuro/uoc_datasci/blob/main/code/session3_live_complete.qmd){target="_blank"} |
| 4 | 22/11/2023 | Data exploration practice (and wk 3 catch up) | N/A | [live coding output](code/week4_live.qmd){target="_blank"} \\ [source](https://github.com/ibsneuro/uoc_datasci/blob/main/code/week4_live.qmd){target="_blank"} \\ [week 4 exercises](https://github.com/ibsneuro/uoc_datasci/blob/main/code/session4_himalayan_expeditions.qmd){target="_blank"} |
| 5 | 29/11/2023 | Importing and tidying data | [slides - importing](slides/d02_01_importing_data.html){target="_blank"} \\ [slides - tidying](slides/d02_02_tidying_data.html){target="_blank"} | [student_teacher_ratios.csv](https://github.com/ibsneuro/uoc_datasci/blob/main/data/student_teacher_ratios.csv){target="_blank"} \\ [live coding output](code/week5.qmd){target="_blank"} \\ [source](https://github.com/ibsneuro/uoc_datasci/blob/main/code/week5.qmd){target="_blank"} |
| 6 | 06/12/2023 | Tidying ctd. / Next steps | [slides - next steps](slides/d03_01_next_steps.html){target="_blank"}  | [primary_school_completion.csv](https://github.com/ibsneuro/uoc_datasci/blob/main/data/primary_school_completion.csv){target="_blank"} \\ [ratio_of_girls_to_boys_in_primary_and_secondary_education_perc.csv](https://github.com/ibsneuro/uoc_datasci/blob/main/data/ratio_of_girls_to_boys_in_primary_and_secondary_education_perc.csv) \\ [live coding output](code/week6.html){target="_blank"} \\ [source](https://github.com/ibsneuro/uoc_datasci/blob/main/code/week6.qmd){target="_blank"} |

### January-February 2024 (zoom sessions)

All sessions will take place at 9 am CET; see Ilias for zoom links and session recordings.

| Week | Date | Topic | Slides | Other Materials |
|------|------|------|------| ------|
| 7 | 09/01/2024 | Joining data frames / working with strings |[slides](slides/d04_01_strings_joins.html){target="_blank"} |[spotify_dataset.csv](https://github.com/ibsneuro/uoc_datasci/blob/main/data/spotify_dataset.csv){target="_blank"} \\ [live coding output](code/session7_live.html){target="_blank"} \\ [source](https://github.com/ibsneuro/uoc_datasci/blob/main/code/session7_live.qmd){target="_blank"}|
| 8 | 25/01/2024 | More on Quarto reports |[slides](slides/d05_01_quarto.html){target="_blank"}|[Quarto example](code/customising_quarto.html){target="_blank"} \\ [source zip](https://github.com/ibsneuro/uoc_datasci/blob/main/code/session8.zip){target="_blank"}|
| 9 | 01/02/2024 | Further tips and tricks |      |      |


## Resources

Any other resources required will be made available here.

